### ISSUE TITLE
Documentation points to non secure Singularity hub

### ISSUE THREAD

**Issue by TormodLandet** [singularityware/singularityware.github.io#56]
The web page http://singularity.lbl.gov/singularity-tutorial points to https://www.singularity-hub.org/ which is not working due to certificate issues. It turns out that  https://singularity-hub.org/ does work (without the www), so this is probably a configuration issue, or they intended for no one to use the www prefix. 

It is of course important to not request certificate security exceptions for a software repository. The security should be high priority.

PS: I could not find a way to report issues with the singularity-hub.org web pages so you might want to tip them of to this problem

**Comment by vsoch** [comment]
Hey @TormodLandet ! Thanks for your remarks. We do have an issue board for singularity hub, and this particular issue is [well known](https://github.com/singularityhub/singularityhub.github.io/issues/2). It is for the exact reasons of security that I don't publicly release the guts of Singularity Hub, but have provided the board for fixing issues. 

The "them" you refer to is just me - I created and maintain the entirety of Singularity Hub. I take security with very high priority, and the issue with the certificate is documented and I will figure out how to get www. working when I re-issue it. I've fixed the link to point to shub without the www, so please let me know if you have any other issues, and feel free to add more to https://github.com/singularityhub/singularityhub.github.io/issues and let us know if we have addressed your issue here. Thanks again for the tips!

**Comment by TormodLandet** [comment]
No problem! Thanks for your work on this! Maybe you can add a link to the issue tracker on https://singularity-hub.org/about ?

**Comment by vsoch** [comment]
you got it!

![image](https://cloud.githubusercontent.com/assets/814322/24113349/ea045f30-0d72-11e7-8314-1de5b00ee969.png)
